"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { listArtists, type Album, type Artist } from "@/lib/catalog";
import { adminCreateAlbum, adminPublish } from "@/lib/admin-catalog";
import { AdminList } from "@/components/admin-list";
import { AdminResourceForm } from "@/components/admin-resource-form";
import { EmptyState, ErrorState, LoadingState } from "@/components/catalog-states";
export default function AdminAlbums(){const[items,setItems]=useState<Album[]>([]);const[artists,setArtists]=useState<Artist[]>([]);const[state,setState]=useState("loading");const[created,setCreated]=useState<Album|null>(null);const[message,setMessage]=useState("");const load=useCallback(()=>{setState("loading");void listArtists(1,100).then(r=>{setArtists(r.data);setItems(r.data.flatMap(a=>(a.albums??[]).map(album=>({...album,artist:{id:a.id,name:a.name,slug:a.slug}}))));setState("ready")}).catch(()=>setState("error"))},[]);useEffect(()=>{queueMicrotask(()=>{void load()})},[load]);return <main className="mx-auto grid max-w-6xl gap-8 px-4 py-10 lg:grid-cols-[360px_1fr]"><AdminResourceForm title="Create album" fields={[{name:"artistId",label:"Artist",required:true,options:artists.map(a=>({value:a.id,label:a.name}))},{name:"title",label:"Title",required:true},{name:"slug",label:"Slug",required:true},{name:"description",label:"Description"}]} onSubmit={async values=>{const r=await adminCreateAlbum({artistId:values.artistId,title:values.title,slug:values.slug,description:values.description});setCreated(r.data);load()}}/>{created?<section className="rounded-[var(--radius-md)] border border-[var(--accent)]/40 bg-[var(--surface)] p-6"><p className="text-sm uppercase tracking-[.2em] text-[var(--accent)]">Album created</p><h2 className="mt-3 text-2xl font-semibold">{created.title}</h2><p className="mt-2 text-sm text-[var(--muted)]">Publish the album before creating tracks.</p>{message&&<p role="status" className="mt-3 text-sm text-[var(--accent)]">{message}</p>}<div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>void adminPublish("albums",created.id).then(()=>setMessage("Album published. You can now create a track.")).catch(()=>setMessage("Could not publish this album."))} className="rounded bg-[var(--accent)] px-4 py-2 font-semibold text-black">Publish album</button><Link href="/admin/tracks" className="rounded border px-4 py-2">Create track</Link><button onClick={()=>setCreated(null)} className="rounded border px-4 py-2">Create another</button></div></section>:<section><h1 className="mb-4 text-2xl font-semibold">Albums</h1>{state==="loading"?<LoadingState/>:state==="error"?<ErrorState/>:!items.length?<EmptyState label="No published albums are visible yet. Create an album above to begin."/>:<AdminList type="albums" items={items} onRefresh={load}/>}</section>}</main>}
