"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { getAlbum, listArtists, type Album, type Artist, type Track } from "@/lib/catalog";
import { adminCreateTrack } from "@/lib/admin-catalog";
import { AdminList } from "@/components/admin-list";
import { AdminResourceForm } from "@/components/admin-resource-form";
import { EmptyState, ErrorState, LoadingState } from "@/components/catalog-states";

type CreatedTrack = { id: string; title: string; artistName: string; albumName: string };

export default function AdminTracks() {
  const [items, setItems] = useState<Track[]>([]); const [albums, setAlbums] = useState<Album[]>([]); const [artists, setArtists] = useState<Artist[]>([]); const [state, setState] = useState("loading"); const [created, setCreated] = useState<CreatedTrack | null>(null);
  const load = useCallback(() => { setState("loading"); void listArtists(1, 100).then(async (result) => { setArtists(result.data); const allAlbums = result.data.flatMap((artist) => artist.albums ?? []); setAlbums(allAlbums); const details = await Promise.all(allAlbums.map((album) => getAlbum(album.slug).then((response) => response.data).catch(() => null))); setItems(details.flatMap((album) => album?.tracks ?? [])); setState("ready"); }).catch(() => setState("error")); }, []);
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);
  return <main className="mx-auto grid max-w-6xl gap-8 px-4 py-10 lg:grid-cols-[360px_1fr]"><AdminResourceForm title="Create track" fields={[{ name: "albumId", label: "Album", required: true, options: albums.map((album) => ({ value: album.id, label: album.title })) }, { name: "artistId", label: "Primary artist", required: true, options: artists.map((artist) => ({ value: artist.id, label: artist.name })) }, { name: "title", label: "Title", required: true }, { name: "slug", label: "Slug", required: true }, { name: "trackNumber", label: "Track number", type: "number", required: true }, { name: "discNumber", label: "Disc number", type: "number", required: true }]} onSubmit={async (values) => { const response = await adminCreateTrack({ albumId: values.albumId, title: values.title, slug: values.slug, trackNumber: Number(values.trackNumber), discNumber: Number(values.discNumber), artists: [{ artistId: values.artistId, creditType: "PRIMARY", position: 0 }] }); const artist = artists.find((item) => item.id === values.artistId); const album = albums.find((item) => item.id === values.albumId); setCreated({ id: response.data.id, title: response.data.title, artistName: artist?.name ?? "Selected artist", albumName: album?.title ?? "Selected album" }); load(); }} />{created ? <section className="rounded-[var(--radius-md)] border border-[var(--accent)]/40 bg-[var(--surface)] p-6"><p className="text-sm uppercase tracking-[.2em] text-[var(--accent)]">Track created successfully</p><h2 className="mt-3 text-2xl font-semibold">{created.title}</h2><p className="mt-2 text-sm text-[var(--muted)]">{created.artistName} · {created.albumName}</p><p className="mt-4 text-sm text-[var(--muted)]">Metadata is ready. Audio still needs to be uploaded.</p><div className="mt-6 flex flex-wrap gap-3"><Link href={`/admin/tracks/${created.id}/upload`} className="rounded bg-[var(--accent)] px-4 py-2 font-semibold text-black">Upload audio →</Link><button onClick={() => setCreated(null)} className="rounded border px-4 py-2">Create another track</button></div></section> : <section><h1 className="mb-2 text-2xl font-semibold">Tracks</h1><p className="mb-4 text-sm text-[var(--muted)]">The list below contains tracks available through the public catalog API. Newly created drafts continue through the workflow above.</p>{state === "loading" ? <LoadingState /> : state === "error" ? <ErrorState /> : !items.length ? <EmptyState label="No published tracks are available yet. Create a track above to begin the metadata → upload → publish workflow." /> : <AdminList type="tracks" items={items} onRefresh={load} />}</section>}</main>;
}
