"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useState } from "react";
import { listArtists, getAlbum, type Album, type Artist, type Track } from "@/lib/catalog";
import { adminCreateTrack } from "@/lib/admin-catalog";
import { AdminList } from "@/components/admin-list";
import { AdminResourceForm } from "@/components/admin-resource-form";
import { EmptyState, ErrorState, LoadingState } from "@/components/catalog-states";
export default function AdminTracks() { const [items, setItems] = useState<Track[]>([]); const [albums, setAlbums] = useState<Album[]>([]); const [state, setState] = useState("loading"); const load = useCallback(() => { setState("loading"); void listArtists(1, 100).then(async (r) => { const allAlbums = r.data.flatMap((a: Artist) => a.albums ?? []); setAlbums(allAlbums); const details = await Promise.all(allAlbums.map((a) => getAlbum(a.slug).then((x) => x.data).catch(() => null))); setItems(details.flatMap((a) => a?.tracks ?? [])); setState("ready"); }).catch(() => setState("error")); }, []); useEffect(load, [load]); return <main className="mx-auto grid max-w-6xl gap-8 px-4 py-10 lg:grid-cols-[360px_1fr]"><AdminResourceForm title="Create track" fields={[{ name: "albumId", label: `Album ID (${albums.length} available)`, required: true }, { name: "title", label: "Title", required: true }, { name: "slug", label: "Slug", required: true }, { name: "trackNumber", label: "Track number", type: "number", required: true }, { name: "discNumber", label: "Disc number", type: "number", required: true }]} onSubmit={async (values) => { await adminCreateTrack({ albumId: values.albumId, title: values.title, slug: values.slug, trackNumber: Number(values.trackNumber), discNumber: Number(values.discNumber), artists: [] }); load(); }} /><section><h1 className="mb-2 text-2xl font-semibold">Tracks</h1><p className="mb-4 text-sm text-gray-600">Audio upload is intentionally deferred to Phase 2D.</p>{state === "loading" ? <LoadingState /> : state === "error" ? <ErrorState /> : !items.length ? <EmptyState label="No tracks are visible through the current catalog API." /> : <AdminList type="tracks" items={items} onRefresh={load} />}</section></main>; }
