"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";

const sections = [
  { label: "WORKSPACE", links: [{ href: "/admin", label: "Dashboard" }, { href: "/admin/artists", label: "Artists" }, { href: "/admin/albums", label: "Albums" }, { href: "/admin/tracks", label: "Tracks" }] },
  { label: "ACCOUNT", links: [{ href: "/account", label: "Account" }] },
  { label: "EXTERNAL", links: [{ href: "/", label: "Public Site" }] },
];

function active(pathname: string, href: string) { return href === "/admin" ? pathname === href : pathname === href || pathname.startsWith(`${href}/`); }

export function AdminShell({ children }: Readonly<{ children: React.ReactNode }>) {
  const { user, status, logout } = useAuth(); const router = useRouter(); const pathname = usePathname(); const [open, setOpen] = useState(false); const [loggingOut, setLoggingOut] = useState(false);
  useEffect(() => { if (status === "unauthenticated") router.replace("/login"); else if (status === "authenticated" && user?.role !== "ADMIN") router.replace("/account"); }, [status, user, router]);
  useEffect(() => { queueMicrotask(() => setOpen(false)); }, [pathname]);
  if (status !== "authenticated" || user?.role !== "ADMIN") return <main className="grid min-h-screen place-items-center p-8 text-[var(--muted)]">Checking admin access…</main>;
  async function handleLogout() { setLoggingOut(true); try { await logout(); router.replace("/login"); } finally { setLoggingOut(false); } }
  const navigation = <div className="grid gap-7">{sections.map((section) => <section key={section.label}><p className="px-3 text-[10px] font-semibold tracking-[.25em] text-[var(--muted)]">{section.label}</p><div className="mt-2 grid gap-1">{section.links.map((link) => <Link key={link.href} href={link.href} className={`rounded-md px-3 py-2.5 text-sm transition ${active(pathname, link.href) ? "bg-[var(--accent)]/15 font-medium text-[var(--accent)]" : "text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-white"}`}>{link.label}</Link>)}</div></section>)}<section><p className="px-3 text-[10px] font-semibold tracking-[.25em] text-[var(--muted)]">SESSION</p><button disabled={loggingOut} onClick={() => void handleLogout()} className="mt-2 w-full rounded-md px-3 py-2.5 text-left text-sm text-[var(--muted)] transition hover:bg-[var(--surface-hover)] hover:text-white disabled:opacity-50">{loggingOut ? "Logging out…" : "Log out"}</button></section></div>;
  return <div className="min-h-screen bg-[var(--background)]"><header className="sticky top-0 z-30 border-b border-[var(--border)] bg-[var(--surface)]/95 backdrop-blur"><div className="mx-auto flex max-w-[1440px] items-center gap-4 px-5 py-4"><button type="button" aria-label="Open admin menu" aria-expanded={open} onClick={() => setOpen(true)} className="rounded border border-[var(--border)] px-3 py-2 text-sm md:hidden">☰</button><Link href="/admin" className="text-lg font-semibold tracking-tight">Audio<span className="text-[var(--accent)]">/</span>Admin</Link><span className="hidden text-sm text-[var(--muted)] md:inline">Workspace</span><div className="ml-auto flex items-center gap-4"><Link href="/" className="hidden text-sm text-[var(--muted)] hover:text-white sm:inline">Public Site</Link><Link href="/account" className="text-sm text-[var(--muted)] hover:text-white">Account</Link><button onClick={() => void handleLogout()} disabled={loggingOut} className="hidden rounded border border-[var(--border)] px-3 py-2 text-sm hover:bg-[var(--surface-hover)] disabled:opacity-50 sm:inline">{loggingOut ? "Logging out…" : "Log out"}</button></div></div></header><div className="mx-auto flex max-w-[1440px]"><aside className="hidden min-h-[calc(100vh-73px)] w-56 shrink-0 border-r border-[var(--border)] bg-[var(--surface)] px-4 py-8 md:block">{navigation}</aside>{open && <div className="fixed inset-0 z-40 md:hidden"><button aria-label="Close admin menu" onClick={() => setOpen(false)} className="absolute inset-0 bg-black/70" /><aside className="relative z-10 h-full w-72 max-w-[85vw] overflow-y-auto border-r border-[var(--border)] bg-[var(--surface)] px-4 py-8">{navigation}</aside></div>}<div className="min-w-0 flex-1"><div className="px-5 pt-5 text-sm text-[var(--muted)]"><div className="flex items-center gap-2"><Link href="/admin" className="hover:text-white">Admin</Link>{pathname !== "/admin" && <><span>/</span>{pathname.includes("/upload") ? <><Link href="/admin/tracks" className="hover:text-white">Tracks</Link><span>/</span><span>Upload Audio</span></> : <span>{pathname.split("/")[2] === "artists" ? "Artists" : pathname.split("/")[2] === "albums" ? "Albums" : "Tracks"}</span>}</>}</div></div>{children}</div></div></div>;
}
