"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { listArtists, type Artist } from "@/lib/catalog";
import { adminCreateArtist, adminPublish } from "@/lib/admin-catalog";
import { AdminList } from "@/components/admin-list";
import { AdminResourceForm } from "@/components/admin-resource-form";
import { EmptyState, ErrorState, LoadingState } from "@/components/catalog-states";
export default function AdminArtists() { const [items,setItems]=useState<Artist[]>([]); const [state,setState]=useState("loading"); const [created,setCreated]=useState<Artist|null>(null); const [message,setMessage]=useState(""); const load=useCallback(()=>{setState("loading");void listArtists(1,100).then(r=>{setItems(r.data);setState("ready")}).catch(()=>setState("error"))},[]);useEffect(()=>{queueMicrotask(()=>{void load()})},[load]);return <main className="mx-auto grid max-w-6xl gap-8 px-4 py-10 lg:grid-cols-[360px_1fr]"><AdminResourceForm title="Create artist" fields={[{name:"name",label:"Name",required:true},{name:"slug",label:"Slug",required:true},{name:"bio",label:"Bio"}]} onSubmit={async values=>{const r=await adminCreateArtist({name:values.name,slug:values.slug,bio:values.bio});setCreated(r.data);load()}}/>{created?<section className="rounded-[var(--radius-md)] border border-[var(--accent)]/40 bg-[var(--surface)] p-6"><p className="text-sm uppercase tracking-[.2em] text-[var(--accent)]">Artist created</p><h2 className="mt-3 text-2xl font-semibold">{created.name}</h2>{message&&<p role="status" className="mt-3 text-sm text-[var(--accent)]">{message}</p>}<p className="mt-3 text-sm text-[var(--muted)]">Publish this artist before creating dependent albums.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>void adminPublish("artists",created.id).then(()=>setMessage("Artist published. You can now create an album.")).catch(()=>setMessage("Could not publish this artist."))} className="rounded bg-[var(--accent)] px-4 py-2 font-semibold text-black">Publish artist</button><Link href="/admin/albums" className="rounded border px-4 py-2">Create album</Link><button onClick={()=>setCreated(null)} className="rounded border px-4 py-2">Create another</button></div></section>:<section><h1 className="mb-4 text-2xl font-semibold">Artists</h1>{state==="loading"?<LoadingState/>:state==="error"?<ErrorState/>:!items.length?<EmptyState label="No published artists are available yet. Create an artist above to begin."/>:<AdminList type="artists" items={items} onRefresh={load}/>}</section>}</main>}
